### ISSUE TITLE
TypeError: super() argument 1 must be type, not classobj in 

### ISSUE THREAD

**Issue by Sucran** [Ahmkel/Keras-Project-Template#3]
Hi @Ahmkel, this repo is really great! thanks for putting the time to implement this.
When I run the code follow the way in README, I have this issue...
```
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    main()
  File "main.py", line 23, in main
    data_loader = SimpleMnistDataLoader(config)
  File "/home/scr/Documents/Keras-Project/data_loader/simple_mnist_data_loader.py", line 7, in __init__
    super(SimpleMnistDataLoader, self).__init__(config)
```

My python version is 2.7.12

**Comment by Sucran** [comment]
This issue is similar to this one on stackoverflow [https://stackoverflow.com/questions/1713038/super-fails-with-error-typeerror-argument-1-must-be-type-not-classobj](url)
